package com.jobCenter.domain;

import java.util.Date;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbggenerated Sat Nov 26 15:46:41 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_code
     *
     * @mbggenerated Sat Nov 26 15:46:42 CST 2016
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_name
     *
     * @mbggenerated Sat Nov 26 15:46:42 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_phone
     *
     * @mbggenerated Sat Nov 26 15:46:42 CST 2016
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_mail
     *
     * @mbggenerated Sat Nov 26 15:46:42 CST 2016
     */
    private String userMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_pwd
     *
     * @mbggenerated Sat Nov 26 15:46:42 CST 2016
     */
    private String userPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.is_del
     *
     * @mbggenerated Sat Nov 26 15:46:42 CST 2016
     */
    private Integer isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.create_id
     *
     * @mbggenerated Sat Nov 26 15:46:42 CST 2016
     */
    private String createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.create_time
     *
     * @mbggenerated Sat Nov 26 15:46:42 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.last_modify_id
     *
     * @mbggenerated Sat Nov 26 15:46:42 CST 2016
     */
    private String lastModifyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.last_modify_time
     *
     * @mbggenerated Sat Nov 26 15:46:42 CST 2016
     */
    private Date lastModifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbggenerated Sat Nov 26 15:46:42 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbggenerated Sat Nov 26 15:46:42 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_code
     *
     * @return the value of user_info.user_code
     *
     * @mbggenerated Sat Nov 26 15:46:42 CST 2016
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_code
     *
     * @param userCode the value for user_info.user_code
     *
     * @mbggenerated Sat Nov 26 15:46:42 CST 2016
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_name
     *
     * @return the value of user_info.user_name
     *
     * @mbggenerated Sat Nov 26 15:46:42 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_name
     *
     * @param userName the value for user_info.user_name
     *
     * @mbggenerated Sat Nov 26 15:46:42 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_phone
     *
     * @return the value of user_info.user_phone
     *
     * @mbggenerated Sat Nov 26 15:46:42 CST 2016
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_phone
     *
     * @param userPhone the value for user_info.user_phone
     *
     * @mbggenerated Sat Nov 26 15:46:42 CST 2016
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_mail
     *
     * @return the value of user_info.user_mail
     *
     * @mbggenerated Sat Nov 26 15:46:42 CST 2016
     */
    public String getUserMail() {
        return userMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_mail
     *
     * @param userMail the value for user_info.user_mail
     *
     * @mbggenerated Sat Nov 26 15:46:42 CST 2016
     */
    public void setUserMail(String userMail) {
        this.userMail = userMail == null ? null : userMail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_pwd
     *
     * @return the value of user_info.user_pwd
     *
     * @mbggenerated Sat Nov 26 15:46:42 CST 2016
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_pwd
     *
     * @param userPwd the value for user_info.user_pwd
     *
     * @mbggenerated Sat Nov 26 15:46:42 CST 2016
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.is_del
     *
     * @return the value of user_info.is_del
     *
     * @mbggenerated Sat Nov 26 15:46:42 CST 2016
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.is_del
     *
     * @param isDel the value for user_info.is_del
     *
     * @mbggenerated Sat Nov 26 15:46:42 CST 2016
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.create_id
     *
     * @return the value of user_info.create_id
     *
     * @mbggenerated Sat Nov 26 15:46:42 CST 2016
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.create_id
     *
     * @param createId the value for user_info.create_id
     *
     * @mbggenerated Sat Nov 26 15:46:42 CST 2016
     */
    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.create_time
     *
     * @return the value of user_info.create_time
     *
     * @mbggenerated Sat Nov 26 15:46:42 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.create_time
     *
     * @param createTime the value for user_info.create_time
     *
     * @mbggenerated Sat Nov 26 15:46:42 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.last_modify_id
     *
     * @return the value of user_info.last_modify_id
     *
     * @mbggenerated Sat Nov 26 15:46:42 CST 2016
     */
    public String getLastModifyId() {
        return lastModifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.last_modify_id
     *
     * @param lastModifyId the value for user_info.last_modify_id
     *
     * @mbggenerated Sat Nov 26 15:46:42 CST 2016
     */
    public void setLastModifyId(String lastModifyId) {
        this.lastModifyId = lastModifyId == null ? null : lastModifyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.last_modify_time
     *
     * @return the value of user_info.last_modify_time
     *
     * @mbggenerated Sat Nov 26 15:46:42 CST 2016
     */
    public Date getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.last_modify_time
     *
     * @param lastModifyTime the value for user_info.last_modify_time
     *
     * @mbggenerated Sat Nov 26 15:46:42 CST 2016
     */
    public void setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }
}